services:
  pedido-postgres:
    image: postgres:16
    container_name: pedido-postgres
    environment:
      POSTGRES_DB: pedido_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # Porta 5433 no seu PC aponta para 5432 dentro do container
    volumes:
      - pedido_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pedido_postgres_data: